name: linter
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: pip install poetry
      - run: make build
      - run: make package-install
      - run: poetry install
      - run: make lint
      - run: make test
      - run: ls -la
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: < "51c4feab561c139044e8f01516dac1f5516911ab5c9843814ef6cdbcb7306417" >
        with:
          coverageCommand: make test-cover
          debug: true