name: linter
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install poetry
      - run: make build
      - run: make package-install
      - run: make lint
      - run: ls -la